package com.ren.dao;

import com.ren.dataObject.PromoDO;
import org.apache.ibatis.annotations.Select;

public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Thu May 06 21:34:27 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Thu May 06 21:34:27 CST 2021
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Thu May 06 21:34:27 CST 2021
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Thu May 06 21:34:27 CST 2021
     */
    PromoDO selectByPrimaryKey(Integer id);


    /*@Select("select * from promo where item_id = #{id}")*/
    PromoDO selectByItemId(Integer item_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Thu May 06 21:34:27 CST 2021
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo
     *
     * @mbg.generated Thu May 06 21:34:27 CST 2021
     */
    int updateByPrimaryKey(PromoDO record);




}